# Generated by Django 5.2.17 on 2026-09-13 22:48

import catalog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Benjamin Locher', max_length=180, unique=True)),
                ('slug', models.SlugField(default='benjamin-locher', max_length=180, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, upload_to='artists/')),
                ('external_ids', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('suno', 'Suno'), ('too_lost', 'Too Lost')], max_length=32, unique=True)),
                ('encrypted_payload', models.TextField()),
                ('display_label', models.CharField(blank=True, max_length=240)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(default='suno', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('albums_seen', models.PositiveIntegerField(default=0)),
                ('tracks_seen', models.PositiveIntegerField(default=0)),
                ('loose_tracks_excluded', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suno_playlist_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('source_cover_url', models.URLField(blank=True, max_length=1000)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=80)),
                ('upc', models.CharField(blank=True, max_length=32)),
                ('label_name', models.CharField(blank=True, default='Benjamin Locher', max_length=180)),
                ('copyright_line', models.CharField(blank=True, max_length=240)),
                ('production_line', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('live', 'Live'), ('withdrawing', 'Withdrawing'), ('withdrawn', 'Withdrawn')], default='draft', max_length=24)),
                ('public', models.BooleanField(default=False)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('too_lost_release_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='catalog.artist')),
            ],
            options={
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('new', 'New release'), ('replacement', 'Replacement'), ('takedown', 'Takedown')], default='new', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('blocked', 'Blocked'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('live', 'Live'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('too_lost_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload_snapshot', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='catalog.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suno_clip_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('lyrics', models.TextField(blank=True)),
                ('timed_lyrics', models.JSONField(blank=True, default=list)),
                ('explicit', models.BooleanField(default=False)),
                ('instrumental', models.BooleanField(default=False)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('isrc', models.CharField(blank=True, db_index=True, max_length=20)),
                ('too_lost_track_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_audio_url', models.URLField(blank=True, max_length=1000)),
                ('source_image_url', models.URLField(blank=True, max_length=1000)),
                ('mp3_file', models.FileField(blank=True, upload_to='tracks/mp3/')),
                ('wav_file', models.FileField(blank=True, upload_to='tracks/wav/')),
                ('audio_status', models.CharField(choices=[('remote', 'Remote only'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('saved', 'Saved'), ('failed', 'Failed')], default='remote', max_length=24)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='catalog.artist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formats', models.JSONField(default=catalog.models.default_audio_formats)),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting confirmation'), ('queued', 'Queued'), ('running', 'Running'), ('saved', 'Saved'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='awaiting_confirmation', max_length=32)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('suno_period', models.CharField(blank=True, max_length=80)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='catalog.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='catalog.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_tracks', to='catalog.track')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='albums', through='catalog.AlbumTrack', to='catalog.track'),
        ),
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('amazon_music', 'Amazon Music'), ('youtube_music', 'YouTube Music'), ('tidal', 'Tidal'), ('deezer', 'Deezer'), ('pandora', 'Pandora'), ('soundcloud', 'SoundCloud'), ('other', 'Other')], max_length=40)),
                ('url', models.URLField(max_length=1000)),
                ('external_id', models.CharField(blank=True, max_length=240)),
                ('object_id', models.CharField(max_length=64)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'content_type', 'object_id'), name='unique_platform_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('artist', 'slug'), name='unique_track_slug_per_artist'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track'), name='unique_track_per_album'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'position'), name='unique_album_track_position'),
        ),
    ]
